### PR TITLE
[iOS/Android] Add config tools for checkmark, crossmark, dot

### PR DESCRIPTION
**Pull request by darrenchann**
add `Config.Tools.annotationCreateCheckMarkStamp`, `Config.Tools.annotationCreateCrossMarkStamp`, `Config.Tools.annotationCreateDotStamp` to android/ios

for testing:

```
const myToolbar = {
      [Config.CustomToolbarKey.Id]: 'myToolbar',
      [Config.CustomToolbarKey.Name]: 'myToolbar', 
      [Config.CustomToolbarKey.Icon]: Config.ToolbarIcons.FillAndSign,
      [Config.CustomToolbarKey.Items]: [Config.Tools.annotationCreateCheckMarkStamp, Config.Tools.annotationCreateArrow, Config.Tools.annotationCreateDotStamp, Config.Tools.annotationCreateCallout]
    };
```
    
```
    <DocumentView
    annotationToolbars={[Config.DefaultToolbars.Annotate, myToolbar]}
    />
```

### CODE REVIEW

**Comment by ama-pdftron** [comment]
You will need to manually update package.json:
https://github.com/PDFTron/pdftron-react-native/pull/671/commits/64b9aaac72653771292dca6150ac74bc7b1d171a

**Comment by darrenchann** [comment]
updated package.json increment

**Comment by darrenchann** [comment]
> The functionality works but I think the naming is a bit inconsistent with other annotation types. I think it would be more consistent if we did: `FormFillCheck` -> `AnnotationCreateCheckMarkStamp` `FormFillCross` -> `AnnotationCreateCrossMarkStamp` `FormFillDot` -> `AnnotationCreateDotStamp`
> 
> and same for the keys in the Config file `formFillCheck` -> `annotationCreateCheckMarkStamp` `formFillCross` -> `annotationCreateCrossMarkStamp` `formFillDot` -> `annotationCreateDotStamp`
> 
> @brandenfung2 what are your thoughts on that?

I went for the suggested change for the names of the configs.

**Review by JamieDass — APPROVED** [review]
Looks good to me, need to wait for Android review to merge.

**Review by brandenfung2 — CHANGES_REQUESTED** [review]
This does not work on Android:
```
disabledTools={[Config.Tools.annotationCreateCrossMarkStamp, Config.Tools.annotationCreateCheckMarkStamp, Config.Tools.annotationCreateDotStamp]}
```

**Review by JamieDass — CHANGES_REQUESTED** [review]
Good catch by Branden.
`setToolMode` and `disabledTools` don't seem to work on iOS.

```
this._viewer.setToolMode(Config.Tools.annotationCreateCrossMarkStamp).then(() => {
      // done switching tools                                                                                                                                                                                                                                                                                                                                       
});
```

```
disabledTools={[Config.Tools.annotationCreateCrossMarkStamp, Config.Tools.annotationCreateCheckMarkStamp, Config.Tools.annotationCreateDotStamp]}
```

**Review by JamieDass — APPROVED** [review]
`setToolMode` is working on iOS.
Currently it is not possible to disable these tools through native APIs so we have added a ticket to our backlog to implement that and once that is done we can add that to the React Native wrapper as well.

**Comment by brandenfung2** [comment]
Added support for setTool and disableTool for Dot, Checkmark, and Cross on Android

**Review by brandenfung2 — APPROVED** [review]

**Pull request merged**
