### PR TITLE
Hygen code generator

### PR DESCRIPTION
**Pull request by kmathew-pdftron**
### Summary 
This is a code-generator meant to automate boilerplate code for React Native props, methods, and event listeners.

### Changes
* Added Hygen Templates and Generators for creating boilerplate code for props, methods, and event listeners in React Native

### Testing 
* Install Hygen in your local machine first by running `npm i -g hygen`
* Within the inner repo of the React Native project:
    * To test `prop-generator`, run the command `hygen prop-generator new`
    * To test `method-generator`, run the command `hygen method-generator new`
    * To test `listener-generator`, run the command `hygen listener-generator new`
* For each command, you will be asked a number of required questions (e.g. name of prop/method, parameters, return type)
* After running the respective commands and answering the questions, you will be able to see changes applied to files

### CODE REVIEW

**Comment by sgong-pdftron** [comment]
please update PR description describing test step and test cases

**Review by sgong-pdftron — CHANGES_REQUESTED** [review]
Doesn't seem to work:


D:\PDFTron-Git\pdftron-react-native>hygen prop-generator new --name maxSignatureCount --type number

Loaded templates: C:\Users\PDFTron\AppData\Roaming\npm\node_modules\hygen\src\templates
Error: I can't find action 'new' for generator 'prop-generator'.

      You can try:
      1. 'hygen init self' to initialize your project, and
      2. 'hygen generator new --name prop-generator' to build the generator you wanted.

      Check out the quickstart for more: http://www.hygen.io/quick-start

Hygen v6.2.0

Available actions:
init: repo, self

**Comment by kmathew-pdftron** [comment]
please try running the command from the inner repo (inside node_modules)

**Comment by terryyoon-pdftron** [comment]
@JamesTron @sgong-pdftron this PR is ready for review again!

**Review by sgong-pdftron — APPROVED** [review]

**Review by JamesTron — APPROVED** [review]

**Pull request merged**
